version: '3'
services:
  mongo:
    image: 'mongo'

  chatsservice:
    build: ../src/chats
    environment:
      DB_HOST: "chats_db"
      DB_PORT: "27017"
    stdin_open: true # Needed to keep the image alive.