
package com.easidiomas.usersservice.clients.imagesservice;

import java.awt.Image;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IImageManager", targetNamespace = "http://service.images.easidiomas.ws.miw/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IImageManager {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ImageProcessingException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadImage", targetNamespace = "http://service.images.easidiomas.ws.miw/", className = "com.easidiomas.usersservice.clients.imagesservice.UploadImage")
    @ResponseWrapper(localName = "uploadImageResponse", targetNamespace = "http://service.images.easidiomas.ws.miw/", className = "com.easidiomas.usersservice.clients.imagesservice.UploadImageResponse")
    public String uploadImage(
        @WebParam(name = "arg0", targetNamespace = "")
        Image arg0)
        throws ImageProcessingException_Exception
    ;

}
