
package com.easidiomas.usersservice.clients.imagesservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ImageProcessingException", targetNamespace = "http://service.images.easidiomas.ws.miw/")
public class ImageProcessingException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ImageProcessingException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ImageProcessingException_Exception(String message, ImageProcessingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ImageProcessingException_Exception(String message, ImageProcessingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.easidiomas.usersservice.clients.imagesservice.ImageProcessingException
     */
    public ImageProcessingException getFaultInfo() {
        return faultInfo;
    }

}
