version: '3'
services:
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
      
  chatsservice:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "mongo"
      DB_PORT: "27017"
      SERVER_PORT: "5000"
    stdin_open: true # Needed to keep the image alive.