version: "3.8"
services:
  neo4j:
    image: neo4j
    container_name: neo4j
    expose:
      - "7474"
      - "7687"
    environment:
      NEO4J_AUTH: neo4j/secret

  usersservice:
    build: ./
    container_name: usersservice
    depends_on:
      - neo4j
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      SERVER_PORT: 5000
      USERS_SERVICE_NEO4J_ADDR: bolt://neo4j:7687