version: "3.8"
services:

  # Kafka cluster orchestrator.
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # Logging and other events queue.
  # Needs to contain the ports declaration.
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "service_logs:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres_db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - "5432"

  neo4j:
    image: neo4j
    container_name: neo4j
    expose:
      - "7474"
      - "7687"
    environment:
      NEO4J_AUTH: neo4j/secret

  redis:
    image: redis
    container_name: redis

############# SERVICES ################
  
  topicmodeling:
    build: ../src/topicmodelingservice/
    container_name: topicmodelingservice
    ports:
      - "5001:5001"
    depends_on:
      - kafka
    environment:
      KAFKA_ENDPOINT: "kafka:9092"
      KAFKA_INPUT_TOPIC: "posts"
      KAFKA_LOGGING_TOPIC: "service_logs"

  postsservice:
    build: ../src/postsservice/
    container_name: postsservice
    ports:
      - "5002:80"
    hostname: postsservice
    depends_on:
      - kafka
      - postgres_db
    environment:
      KAFKA_ENDPOINT: "kafka:9092"
      POSTGRES_ENDPOINT: "postgres_db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}

  imagesservice:
    build: ../src/imagesservice/
    ports:
      - "5004:5000"
    depends_on:
      - kafka
  
  texttospeech:
    build: ../src/texttospeechservice/
    container_name: texttospeechservice
    ports:
      - "5003:5000"
    depends_on:
      - kafka
    environment: 
      KAFKA_ENDPOINT: "kafka:9092"
  
  usersservice:
    build: ../src/usersservice/
    container_name: usersservice
    depends_on:
      - neo4j
    expose:
      - "5000"
    environment:
      SERVER_PORT: 5000
      USERS_SERVICE_NEO4J_ADDR: bolt://neo4j:7687

  authservice:
    build: ../src/authenticationservice/
    container_name: authservice
    depends_on:
      - usersservice
    expose:
      - "5000"
    environment:
      USERS_SERVICE_ADDR: usersservice:5000
      USERS_SERVICE_HOST: usersservice
      USERS_SERVICE_PORT: 5000

  statisticsservice:
    build: ../src/statisticsservice/
    container_name: statisticsservice
    depends_on:
      - redis
    expose:
      - "5000"
    environment:
      REDIS_ADDR: redis
      REDIS_PORT: 6379

  apigateway:
    build: ../src/apigateway/
    container_name: apigateway
    depends_on:
      - authservice
      - statisticsservice
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      SERVER_PORT: 5000
      AUTH_SERVICE_ADDRESS: authservice:5000
      USERS_SERVICE_HOST: usersservice
      USERS_SERVICE_PORT: 5000
      STATS_SERVICE_WDSL: "http://statisticsservice:5000/soapws/statistics?wsdl"


############ ELK AND ITS PUTA MADRE ###############

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      discovery.type: single-node

  logstash:
    image: docker.elastic.co/logstash/logstash:$ELK_VERSION
    container_name: logstash
    expose:
      - "5044"
      - "5000"
      - "9600"
    volumes:
      - type: bind
        source: ./config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./config/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - type: bind
        source: ./config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    depends_on:
      - elasticsearch


volumes:
  elasticsearch:
  postgres: